/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackTop: typeof import('./src/components/BackTop.vue')['default']
    CodeBlockComponent: typeof import('./src/components/CodeBlockComponent.vue')['default']
    CustomParagraphComponent: typeof import('./src/components/CustomParagraphComponent.vue')['default']
    Drawer: typeof import('./src/components/drawer.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    InsertMenu: typeof import('./src/components/InsertMenu.vue')['default']
    MComment: typeof import('./src/components/m-comment.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
